float32 distance
bool distance_active
float32 emissivity # minimum: 0, maximum: 1, example: 0.997
bool emissivity_active
float32 ambient # minimum: 0, example: 293.15
bool ambient_active
bool show_on_trigger
bool active
string label
int16 x # minimum: 0, example: 10
int16 y
int16 width
int16 height
bool calc_max_temp
bool calc_max_pos
bool calc_min_temp
bool calc_min_pos
bool calc_avg
bool calc_iso
bool calc_free_form_mask
string free_form_mask
float32 max_x # readOnly: true
float32 max_y # readOnly: true
float32 max_t # readOnly: true
float32 max_valid # readOnly: true
float32 min_x # readOnly: true
float32 min_y # readOnly: true
float32 min_t # readOnly: true
float32 min_valid # readOnly: true
float32 avg_t # readOnly: true
float32 avg_valid # readOnly: true
float32 iso_t # readOnly: true
float32 iso_valid # readOnly: true
---
int16 status_code
string message