string id # readOnly: true
bool active
string label
bool triggered # readOnly: true
int16 duration
float32 value
string condition # Enum: [ MATCH, ABOVE, BELOW ]
float32 hysteresis
string measure_func_type # Enum: [ spot, mbox, mline, mpolyline, reftemp, diff ]
string measure_func_id
string measure_func_res # Enum: [ value_t, max_t, min_t, avg_t, isoCoverage ]
AlarmActions actions	
---
int16 status_code
string message